### ISSUE TITLE
Towards building natively on Windows

### ISSUE THREAD

**Issue by dennisguse** [TheTelephone/TheTelephone#15]
It would be great to build the externals for use on Windows using the native tools.

I think, we could go checkout visual studio together with scoop http://scoop.sh/

**Comment by Schroedingers-Cat** [comment]
It'd start with Visual Studio Code (https://code.visualstudio.com/) as it is free and open source and doesn't need 10GB to install. Additionally, I installed the Visual C++ Build Tools (Visual C++ compilers). 
After that, I installed three extensions for VSC: 
- C/C++
- CMake
- CMake Tools

I also installed CMake via chocolatey (https://chocolatey.org/) to double check my progress.

To run VSC with the CMake Tools properly, I have to start it from the `Visual C++ 2015 x86 Native Build Tools Command Prompt`.

So when running CMake (configured to x86) with this project, the first error I get is 

> LINK : fatal error LNK1104: cannot open file 'fftw3.lib'

So I got the fftw3 library for Win x86 from here ftp://ftp.fftw.org/pub/fftw/bcb-fftw3.zip and the header files from here ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll32.zip. I placed the files relative to this repository `src/include/`
- fftw3.lib
- fftw3.def
- fftw3.h

But that doesn't fix the problem. I also tried to generate the .lib file from the dll using

> lib /def:libfftw3-3.def

and renaming it to `fftw3.lib`, but that didn't help either.

You had one more question in your mail, I just quote it here:

> Which compiler did you use?

Well, honestly I don't know! 
Guessing from the log, the linker is installed to `C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe` and the compiler is installed to `C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe`. However, I'm not sure how to `install include`, as I just moved the files CMake is complaining about to the src/include directory. Is that, what you wanted to know?
The compiler is called `Microsoft Visual Studio 14.0` in CMake.

I also tried to move the fftw3.lib to the path of the link.exe, but that didn't help either. Where expects cmake the fftw3.lib file?

**Comment by chohner** [comment]
This is way messier than I expected (first time compiling on win). Things I found while googling: There's several package manager solutions, most notably the already mentioned [chocolatey](https://chocolatey.org/install) but also [nuget](https://www.nuget.org) and the windows tool [PowerShell Package Manager  aka package manager manager aka oneget](http://www.tomsitpro.com/articles/windows-10-powershell-package-manager,2-16.html) (included in win10).

`choco install` can be used to install build tools but I don't have a good grasp of whats actually needed (`git`, `cmake.portable` and `nuget.commandline` seem like a safe choice, not sure whether `microsoft-build-tools` or `mingw` are needed).

Dependencies seem like an annoying issue. Some are straightforward (`nuget install libfftw`, `choco install opus-tools speex`) but most are not:

`libwebsockets` you probably need to [get yourself](https://github.com/warmcat/libwebsockets), same with [libjson](https://github.com/vincenthz/libjson) and [libsndfile / libresample](http://www.mega-nerd.com)

For libgsm, I found https://github.com/atraczyk/gsm and http://www-uxsup.csx.cam.ac.uk/pub/windows/cygwin/x86_64/release/gsm/ but there's still the [original source](http://www.quut.com/gsm/gsm-1.0.16.tar.gz)

**Comment by dennisguse** [comment]
Long Story short: MSVC cannot be used to build.

The actual issue is that MSCV does not something like this (see C2057):
```
function (unsigned int a) {
  int array[a];
}
```

Reproducablity:
* Install http://landinghub.visualstudio.com/visual-cpp-build-tools
* Install https://cmake.org/download/
* Put m_pd.h into include path (C:\Program\Microsoft Visual Studio 14.0\VC\include)
* Change CMakeLists.txt: replace ~ with tilde (character not supported)
* Change CMakeLists.txt: set(CMAKE_SHARED_LINKER_FLAGS "/FORCE")

Run:
cmake .
cmake --build

Next stop: mingw? or clang?

**Comment by Schroedingers-Cat** [comment]
I tried to compile with MinGW today. 
* install TDM-GCC-64 from here: http://tdm-gcc.tdragon.net/
* put m_pd.h into TDM-GCC-64-path/include
* put OpenSSL (from here https://sourceforge.net/projects/openssl) includes into TDM-GCC-64-path/include and libs into TDM-GCC-64-path/lib

When configuring CMake to generate MinGW files, it succeeds in finding m_pd.h and OpenSSL. So the next stop are libfftw3 and libsndfile. I did:
* install libsndfile from here http://www.mega-nerd.com/libsndfile/ and put its lib and include files into the corresponding compiler paths
* install FFTW3 from here http://www.fftw.org/install/windows.html and put its *.dll and *.def files to  /lib and *.h-Files to /include

Again configuring CMake to generate MinGW files, it still won't find libsndfile and libfftw3:
```cmake
The C compiler identification is GNU 5.1.0
The CXX compiler identification is GNU 5.1.0
Check for working C compiler: C:/tools/TDM-GCC-64/bin/gcc.exe
Check for working C compiler: C:/tools/TDM-GCC-64/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/tools/TDM-GCC-64/bin/g++.exe
Check for working CXX compiler: C:/tools/TDM-GCC-64/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Looking for lws_create_context
Looking for lws_create_context - not found
Looking for include file m_pd.h
Looking for include file m_pd.h - found
Found OpenSSL: C:/Program Files/OpenVPN/bin/ssleay32.dll;C:/Program Files/OpenVPN/bin/libeay32.dll (found version "1.0.2j") 
CMake Warning at CMakeLists.txt:88 (message):
  CLOCK_MONOTONIC not available(Linux/FreeBSD only): benchmark_delay~ will
  not be build.


CMake Warning at CMakeLists.txt:95 (message):
  sys_exit() not available(Linux only): exit will not be build.


CMake Warning at CMakeLists.txt:107 (message):
  libsndfile not found: readsfnow~ and writesfnow~ will not be build.


CMake Warning at CMakeLists.txt:118 (message):
  libfftw3 or libsndfile not found: convolve_dynamic~ will not be build.


CMake Warning at CMakeLists.txt:126 (message):
  libjson-c, OpenSSL, or libwebsockets (compatible version) not found:
  websocket_recv_client and websocket_recv_server will not be build.


CMake Warning at CMakeLists.txt:149 (message):
  libgsm not found: gsm~ will not be build.


CMake Warning at CMakeLists.txt:169 (message):
  libopus not found: opus~ will not be build.


CMake Warning at CMakeLists.txt:177 (message):
  libspeex not found: speex~ will not be build.


Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
Configuring done
```

**Comment by dennisguse** [comment]
Current state - works for externals NOT requiring any external library.

Current state can be found in branch `windows`: https://github.com/TheTelephone/TheTelephone/tree/windows

This is ONLY tested to work on Linux.
Will test the Windows part tomorrow.

**Comment by dennisguse** [comment]
Update: 
* works on Windows
* works on Linux

Added instructions to README.md.

**Comment by chohner** [comment]
Also runs fine on OSX
